#+title: Now
#+slug: index
#+date: <2025-08-19 Tue 20:09:00>

This is a [[https://nownownow.com/about][/now]] page.

* Work

- I am now supporting AWS, DevOps, GitHub, & GitLab as an SME for [[https://kpmg.com/us/en.html][KPMG]].
- Getting through a very busy SOC/SOX portfolio of clients this year. Blogging and other hobbies have taken a hit as a result.

* Media

As I noted above, I'm working a ton right now and my media consumption has dropped down to "can be played in the background" shows and PvP games that don't require much though.

- Playing some games:
  - Halo Infinite
  - Rocket League
- Watching some shows:
  - Bob's Burgers
  - Northern Exposure

* Tech

- Moved my source code back to [[https://sourcehut.org][Sourcehut]] and made the GitHub versions mirrors of Sourcehut.
- Deleted a bunch of accounts to reduce online footprint. Looking for more ways
  to reduce.

* Hobbies

- Built a sandbox with seats that collapse into a lid. I also have enough leftover lumber to build a cubby-type bookshelf.

View the historical [[https://git.sr.ht/~cxc/cleberg.net/log/main/item/content/now/index.org][log of changes]] for this page.
