#+title: Now
#+slug: index
#+date: <2025-11-01 Sat 18:52:08>

This is a [[https://nownownow.com/about][/now]] page.

* Work

- Finally through the end of my 9/30 clients, and focusing on my 12/31
  engagements now.
- Autumn is transforming my area toward winter, so less outdoor activities and
  work. Instead, we're cleaning up the outside in preparation for winter and
  focusing on indoor hobbies.

* Media

- Playing some games:
  - Cyberpunk 2077
  - Old School Runescape
  - Runescape 3
  - Rocket League
- Watching some shows:
  - Cheers
  - Jujutsu Kaisen
  - Mork & Mindy
  - Northern Exposure
  - The Fragrant Flower Blooms with Dignity

* Tech

- Desperately searching for ideas to build that interest me personally. I build
  analytical solutions at work often, but haven't built anything personal in a
  while.
- Deleted /even more/ online accounts. I believe I started around 300+ in my
  password manager around a year ago and I'm down to ~150. I'm running into the
  point where the remainder are accounts I simply can't delete right now.

* Hobbies

- I don't have time for hobbies right now 🙃

View the historical [[https://git.cleberg.net/cleberg.net.git/log/content/now/index.org][log of changes]] for this page.
