# Site settings
base_url = "https://cleberg.net"
title = "cleberg.net"
description = "The personal website of Christian Cleberg."
author = "Christian Cleberg"

# RSS settings
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [{ theme = "dracula", filename = "syntax-theme-dark.css" }]
external_links_target_blank = true
lazy_async_image = true

[extra]
