# Site settings
base_url = "https://cleberg.net"
title = "cleberg.net"
description = "The personal website of Christian Cleberg."
author = "Christian Cleberg"

# RSS settings
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
    { theme = "inspired-github", filename = "syntax-theme-light.css" },
]
external_links_target_blank = true
lazy_async_image = true

[extra]
