#+title: Services & Hosting
#+date: <2025-08-22>

* Domain Registration

- [[https://njal.la][Njalla]]: Migrated all domains to Njalla. Some spare domains left on Cloudflare
  until I figure out if someone wants them or if I can just delete them
  outright.

* DNS

- [[https://njal.la][Njalla]]: I am using their name servers and DNS for my domain traffic.
- [[https://mullvad.net][Mullvad]]: Since I use Mullvad's VPN on most of my devices, I am using their DNS
  with occasional content blockers enabled.
- [[https://nextdns.io][NextDNS]]: Lastly, I enforce NextDNS's DNS at the router level on my home
  network so that any device without a VPN is still slightly protected and not
  using my ISP's DNS.

* Hosting

** Web

- N/A: I currently host all of my services on my server at home via Cox's
  residential fiber network. Since I have accounts on AWS, Azure, GCP, & IBM for
  my job, I use these as temporary backup solutions if I'm away from home and a
  service goes down that I need to use.

** Email

- [[https://migadu.com/][Migadu]]: I've used a few different email providers over the last few years, but
  keep coming back to Migadu due to their drop-dead simplicity and proven
  reliability.

** Source Code

- [[https://sourcehut.org/][Sourcehut]]: I flip back and forth between Sourcehut and GitHub, but I'm
  currently using Sourcehut. I love the minimal form factor and the company's
  mission, but tend to use GitHub to explore other's code.
